### ISSUE TITLE
I created an internal version of this repo

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL/PSSE2PLEXOS#22]
@NREL/nrel-plexos-users I created an NREL internal version of this repository in addition to this one.
NREL employees, please run the following commands from your local repository or submodule directory for this repository:

add remote

``` bash
git remote add internal git@github.nrel.gov:PCM/PSSE2PLEXOS.git
```

to push externally to this github.com repository (note that `<branch name>` is usually `origin`

``` bash
git push origin <branch name>
```

to push internally to the github.nrel.gov repo

``` bash
git push internal <branch name>
```

**Comment by aliehlen1** [comment]
internal repo no longer exists
